site_name: Cataclysm

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WalberthLopes
      name: WalberthLopes GitHub

copyright: Copyright &copy; 2021 - 2022 Cataclysm - By WalberthLopes

theme:
  palette:
    scheme: slate
    primary: orange

  font:
    text: Kanit

  features:
    - navigation.tabs
    - navigation.tabs.sticky

  name: material

  language: pt-BR

  favicon: server-icon.png

  logo: server-icon.png

nav:
  - Home: index.md
  - Regras: regras.md
  - Tutoriais: tutoriais.md
  - Updates: updates.md
  - Loja: loja.md
  - Formulário: form.md
