site_name: Cube Cave

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WalberthLopes
      name: WalberthLopes GitHub

copyright: Copyright &copy; 2021 - 2022 Cube Cave - By WalberthLopes

theme:
  palette:
    scheme: slate
    primary: orange

  font:
    text: Roboto

  features:
    - navigation.tabs
    - navigation.tabs.sticky

  name: material

  language: pt-BR

  favicon: resources/image/server-icon.png

  logo: resources/image/server-icon.png

nav:
  - HOME: index.md
  - REGRAS: regras.md
  - TUTORIAIS: tutoriais.md
  - UPDATES: updates.md
  - LOJA: loja.md
  - VAGAS: form.md
  - STAFF: staff.md
